// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2025/2/15 10:53:51
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["E:/project/baixing/components/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/project/baixing/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/project/baixing/components/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/project/baixing/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/project/baixing/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/project/baixing/plugins/**/*.{js,ts,mjs}","E:/project/baixing/composables/**/*.{js,ts,mjs}","E:/project/baixing/utils/**/*.{js,ts,mjs}","E:/project/baixing/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","E:/project/baixing/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","E:/project/baixing/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;